# Changes here will be overwritten by Copier
_commit: 4d4d95a
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: python
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Minimum viable chat components
project_name: chatom
python_version_primary: '3.11'
team: the chatom authors
